baseURL = "https://aleksgorbenko.dev/"
languageCode = "en-us"
title = "aleks Gorbenko"
theme = "hugo-ink"

copyright = "© aleks Gorbenko {a_G}"

pygmentsstyle = "autumn"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "later"
# disqusShortname = "test"

[params]
	subtitle = "Meditations on Strategy and Tech."

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

[[menu.main]]
name = "Now"
url = "/now"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/aleksgorbenko"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/aleks-gorbenko-software-engineer/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/aleksgbko"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/aleksgbko"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# Enable tags.
[taxonomies]
   tag = "tags"
