baseURL = "https://aleksgorbenko.dev/"
languageCode = "en-us"
title = "aleks Gorbenko"
theme = "hugo-ink"

copyright = "© {a_G}"

pygmentsstyle = "paraiso-dark"
pygmentscodefences = true

enableRobotsTXT = true

# googleAnalytics = "later"
# disqusShortname = "test"

[params]
subtitle = "{a_G} | Meditations on Strategy and Tech."

# Optional 64x64 avatar image.
avatar = "images/aleks_gorbenko_memoji.png"

# Content types to disable Disqus on.
disableDisqusTypes = ["page"]

featherIconsCDN = true
maxTags = 3
wpm = 250
toc = true

mode = "auto" # "dark" or "auto"
customCSS = "css/custom.css"  # Custom CSS applied to default styles.
customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

[[menu.main]]
name = "Now"
url = "/now"
weight = 3

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/aleksgorbenko"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/aleks-gorbenko-software-engineer/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/aleksgbko"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/aleksgbko"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# Enable tags.
[taxonomies]
tag = "tags"
